"""
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""


import math


def NumberOfFactors(number):
    
    n_factors = 0
    i = 1
    
    while i < int(math.sqrt(number)+1):
        if number % i == 0:
            if i * i != number:
                n_factors += 2
            else:
                n_factors += 1
            
        i+=1
        
    #print("{} has {} factors".format(number, n_factors))
    return n_factors + 1 #and itself


def NthTriangularNumber(n):
    return int(n * (n+1) / 2)



triangular_number_n = 1
triangular_number = 1
triangular_number_factors=1
n_factors_needed = 500

while triangular_number_factors <= n_factors_needed:
    triangular_number_n += 1
    triangular_number = NthTriangularNumber(triangular_number_n)
    triangular_number_factors = NumberOfFactors(triangular_number)
    print("Triangular number {} is {}, which has {} factors".format(triangular_number_n, triangular_number, triangular_number_factors))
    
print("First triangular number with over {} factors: {}".format(n_factors_needed, triangular_number))